### ISSUE TITLE
Bug Issue: "About" section in the Profile page.

### ISSUE THREAD

**Issue by Qlify** [Dame2Dolla/TechyDev#18]
when writing in the "About" box capital letters don't get updated. 

for example i want to update my bio to "Hello my name is Adyan" upon clicking update,
it will be displayed without a capital letter for my name "Hello my name is adyan". 
The only capital letter that stays is the first letter.

How to replicate this bug:

Step 1: Navigate to the Sign-up Page and update your "About" profile to "Hello my name is <Your name with capital letter>"  
Step 2: Press update and check the "About" section in your profile.

**Comment by Patrick-Frendo** [comment]
Ah that is due to the sanitation filters in the code. I'll update the code accordingly. 
Again please provide screenshot to make sure i understood what the problem is. 
Fucntion for About has been changed from this:
![image](https://user-images.githubusercontent.com/16851267/236207530-9bc9b1da-1841-44d5-875f-4fe09f3da8a6.png)

To this:
![image](https://user-images.githubusercontent.com/16851267/236207570-a65e19a4-018c-42f5-a8e5-0aa9b813e48d.png)

Re-open if this wasn't what you meant.

**Comment by Qlify** [comment]
Amazing the issues is fixed the about section can have Uppercase letters anywhere now! 
![image](https://user-images.githubusercontent.com/99338407/236209553-b1a14165-bf4a-4249-ac6d-00265df25019.png)
